### ISSUE TITLE
mothur database issue

### ISSUE THREAD

**Issue by splaisan** [a-h-b/dadasnake#26]
Hi Anna,

I tried to download files from the mothur and decipher sites as suggested in the readme but when I link them in the config, mothur does not seem to work.

for mothur I downloaded from thir wiki link [Full-length sequences and taxonomy references](https://mothur.s3.us-east-2.amazonaws.com/wiki/silva.nr_v138_1.tgz)  and untar'ed to /data/biodata/mothur_taxonomy:
* silva.nr_v138_1.align
* silva.nr_v138_1.fasta
* silva.seed_v138_1.align
* silva.seed_v138_1.tax

these 4 files do not match the command reported in the error log

for decipher I downloaded and unzipped to /data/biodata/decipher_taxonomy
* SILVA_SSU_r138_2019.RData

Then I edited my yaml as:

```
taxonomy:
  mothur:
    do: true
    db_path: "/data/biodata/mothur_taxonomy"
    tax_db: "silva.nr_v138_1"
  decipher:
    do: false
    db_path: "/data/biodata/decipher_taxonomy"
    tax_db: "SILVA_SSU_r138_2019.RData"
    db_short_names: "SILVA_SSU_r138"
```

If not correct, would you have a primer on how to install SSU references for mothur.
Or at least the listing of your database folder to see which files are expected there.

Thanks in advance

## mothur error log

```
Script Mode


mothur > set.dir(tempdefault=/data/biodata/mothur_taxonomy)
Mothur's directories:
tempDefault=/data/biodata/mothur_taxonomy/

mothur > 
            classify.seqs(fasta=sequenceTables/all.seqs.for_SILVA_138_SSURef_NR99_cut.fasta, template=silva.nr_v138_1.fasta, taxonomy=silva.nr_v138_1.taxonomy, cutoff=60, method=wang, processors=1)

Using 1 processors.
Unable to open silva.nr_v138_1.fasta. Trying default /data/biodata/mothur_taxonomy/silva.nr_v138_1.fasta.
Unable to open /data/biodata/mothur_taxonomy/silva.nr_v138_1.fasta. Trying mothur's executable location /opt/biotools/dadasnake/conda/ec4abc68013d874fa157380f1e65649f/bin/silva.nr_v138_1.fasta.
Unable to open /opt/biotools/dadasnake/conda/ec4abc68013d874fa157380f1e65649f/bin/silva.nr_v138_1.fasta.
Unable to open silva.nr_v138_1.fasta
Unable to open silva.nr_v138_1.taxonomy. Trying default /data/biodata/mothur_taxonomy/silva.nr_v138_1.taxonomy.
Unable to open /data/biodata/mothur_taxonomy/silva.nr_v138_1.taxonomy. Trying mothur's executable location /opt/biotools/dadasnake/conda/ec4abc68013d874fa157380f1e65649f/bin/silva.nr_v138_1.taxonomy.
Unable to open /opt/biotools/dadasnake/conda/ec4abc68013d874fa157380f1e65649f/bin/silva.nr_v138_1.taxonomy.
Unable to open silva.nr_v138_1.taxonomy
[ERROR]: did not complete classify.seqs.

mothur > quit()
```
